package com.madai.mock;

import javax.swing.text.html.Option;
import java.io.IOException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//@EnableAutoConfiguration
public class App {

    public static void main(String[] args) throws IOException {
        String config = args != null && args[0] != null ? args[0] : "/Users/apple/mock-config/";
        Bootstrap.startMockServer(9233, config);
    }
}
